### ISSUE TITLE
Leaver its not a constructor

### ISSUE THREAD

**Issue by officialdittaz** [CesiumLabs/canvacord#120]
Hi, i got some error when running my bot

TypeError: canvacord.Leaver is not a constructor
    at WelcomeType3 (/home/runner/Extreamable/message/group.js:207:14)
    at module.exports (/home/runner/Extreamable/message/group.js:285:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: canvacord.Leaver is not a constructor
    at WelcomeType3 (/home/runner/Extreamable/message/group.js:207:14)
    at module.exports (/home/runner/Extreamable/message/group.js:285:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

and my code is
const WelcomeType3 = async(id, text1, desc1, gam1, gam2, but = [], options = {}) => {	
try{
const canvacord = require("canvacord");
  
if(Add){
var image3 = new canvacord.Welcomer()
        .setUsername(pushname)
        .setDiscriminator("extream")
        .setMemberCount(allmem)
        .setGuildName(groupName)
        .setAvatar(gam1)
        .setColor("border", "#eb26dd")
        .setColor("username-box", "#eb26dd")
        .setColor("discriminator-box", "#eb26dd")
        .setColor("message-box", "#eb26dd")
        .setColor("title", "#eb26dd")
        .setColor("avatar", "#eb26dd")
        .setText("member-count", "Total")
        .setText("title", "welcome")
        .setText("message", "welcom in gc")
} else if(Remove){
var image3 = new canvacord.Leaver()
        .setUsername(pushname)
        .setDiscriminator("extream")
        .setMemberCount(allmem)
        .setGuildName(groupName)
        .setAvatar(gam1)
        .setColor("border", "#eb26dd")
        .setColor("username-box", "#eb26dd")
        .setColor("discriminator-box", "#eb26dd")
        .setColor("message-box", "#eb26dd")
        .setColor("title", "#eb26dd")
        .setColor("avatar", "#eb26dd")
        .setText("member-count", "Total")
        .setText("title", "welcome")
        .setText("message", "welcom in gc")
}
let foto = await getRandom(".png")
image3.build()
        .then(data => {
            canvacord.write(data,foto);
        });

let gambar = await fs.readFileSync(foto)

let buttonMessage = {
    contextInfo:options,
    image: gambar,
    caption: text1,
    footer: desc1,
    buttons: but,
    headerType: 4
}

await client.sendMessage(id, buttonMessage, options)
await fs.unlinkSync(foto)
  
} catch(err){
console.log(err)
let autoButton = Remove? butOut : butIn
await client.sendButImage(id, text1, desc1, gam1, autoButton, options)
}
}

anyone help me please

**Comment by officialdittaz** [comment]
npm i discord-canvas
